stages:
  - build
  - deploy

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

pages:
  stage: deploy
  image: rust:latest
  before_script:
    - mkdir -p 'public'
  script:
    - cargo run -- --verbose --output 'public' --input 'examples/full/'
  artifacts:
    paths:
      - public
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
